[package]
name = "tun2socks"
version = "0.1.4"
authors = ["hev <r@hev.cc>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/heiher/tun2socks"
description = "High performance tun2socks"

[build-dependencies]
cc = { version = "1.2.1", features = ["parallel"] }
