[package]
name = "tun2socks"
version = "0.1.9"
edition = "2024"
authors = ["hev <r@hev.cc>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/heiher/tun2socks"
description = "High performance tun2socks"
